version: '3.8'
services:

#  app:
#     build: ./
#     ports:
#       - 8008:8080
#     depends_on:
#      - mongodb

  mongodb:
   image: mongo
   ports:
     - 27017:27017
   volumes:
     - dbdata:/data/db

volumes:
  dbdata: